version: '3'

services:

  nginx:
    image: nginx:1.24.0-alpine3.17-slim
    ports:
      - 8080:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build:
      context: .
    ports:
      - 3000:3000
    entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    volumes:
      - ./src:/home/node/app
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
